import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import { TRPCProvider } from "@/app/providers";
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} antialiased`}
      >
        <TRPCProvider>
         <div className="font-sans flex flex-col min-h-screen">
               {/* Header */}
               <header className="w-full bg-white">
                 <div className="max-w-screen-xl mx-auto px-4">
                   <Header />
                 </div>
               </header>
         
               {/* Main content */}
               <main className="flex-1 w-full">
                 <div className="max-w-screen-xl mx-auto px-4">
                   {children}
                 </div>
               </main>
         
               {/* Footer */}
               <footer className="w-full bg-white">
                 <div className="max-w-screen-xl mx-auto px-4">
                   <Footer />
                 </div>
               </footer>
             </div>
        </TRPCProvider>
      </body>
    </html>
  );
}
